dist: trusty
sudo: false

language: node_js
node_js:
  - '13.8'

addons:
  chrome: stable

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - ng lint
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
