dist: trusty
sudo: false

language: node_js
node_js:
  - '13.8'

addons:
  chrome: stable

before_script:
  - npm install -g --silent @angular/cli@9.0.1

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - ng lint
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
